In [11]:
import numpy as np
import lightgbm as lgb
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd

In [3]:
iris = load_iris()
X = iris.data
y = iris.target

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=0)


In [6]:
X_train

array([[6.4, 3.1, 5.5, 1.8],
       [5.4, 3. , 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.2]])

In [10]:
y_train

array([2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0, 0, 1, 2, 2, 2, 2, 1, 2,
       1, 1, 2, 2, 2, 2, 1, 2, 1, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0,
       1, 0, 2, 1, 0, 1, 2, 1, 0, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2,
       0, 0, 2, 0, 0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1,
       0, 2, 0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 2, 2, 0, 1,
       1, 1, 1, 0, 0, 0, 2, 1, 2, 0])

In [9]:
gbm = lgb.LGBMClassifier(objective='multiclass')
gbm.fit(X_train, y_train)
y_pred = gbm.predict(X_test, num_iteration=gbm.best_iteration_)
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

In [12]:
# evaluate using ROC
from sklearn.metrics import roc_auc_score
y_pred_proba = gbm.predict_proba(X_test, num_iteration=gbm.best_iteration_)
y_pred_proba

array([[4.22223322e-05, 6.33162742e-03, 9.93626150e-01],
       [1.46967821e-04, 9.87875248e-01, 1.19777838e-02],
       [9.99775929e-01, 2.23728458e-04, 3.42457935e-07],
       [2.98824495e-05, 4.50322508e-03, 9.95466892e-01],
       [9.99933535e-01, 6.61001414e-05, 3.64405419e-07],
       [1.28721415e-05, 3.16028689e-04, 9.99671099e-01],
       [9.99919413e-01, 8.02227031e-05, 3.64290852e-07],
       [3.92979032e-06, 9.99955981e-01, 4.00895021e-05],
       [5.77990828e-06, 9.99847326e-01, 1.46893999e-04],
       [6.84494061e-05, 9.95426922e-01, 4.50462886e-03],
       [2.33445356e-04, 2.35413502e-01, 7.64353052e-01],
       [4.37425804e-06, 9.99963551e-01, 3.20746118e-05],
       [5.07559452e-05, 9.95847243e-01, 4.10200082e-03],
       [5.68401387e-06, 9.99882073e-01, 1.12242724e-04],
       [4.48220385e-05, 9.96888010e-01, 3.06716755e-03],
       [9.99940556e-01, 5.90794625e-05, 3.64407977e-07],
       [7.89324414e-06, 9.99576778e-01, 4.15329170e-04],
       [5.61429198e-06, 9.99790